FROM java:8
# EXPOSE 8080
# ADD ./target/WithTwitter4j-1.0-SNAPSHOT.jar WithTwitter4j-1.0-SNAPSHOT.jar
# ENTRYPOINT ["java","-jar","WithTwitter4j-1.0-SNAPSHOT.jar"]
CMD mvn clean package
CMD java -jar ./target/WithTwitter4j-1.0-SNAPSHOT.jar
